github action to check that crowdin-generated files are not modified

diff --git a/.github/workflows/translations.yml b/.github/workflows/translations.yml
--- a/.github/workflows/translations.yml
+++ b/.github/workflows/translations.yml
@@ -51,3 +51,30 @@ jobs:
               echo "i18n files are out of date. Please run `pnpm i18n-file-gen` and `./ui/build --i18n` and commit the changes.";
               exit 1;
           fi
+
+  dests-unmodified-check:
+    runs-on: ubuntu-latest
+    #if: github.event_name == 'pull_request' && github.event.pull_request.title != 'New Crowdin updates'
+    env:
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    steps:
+      - uses: actions/checkout@v6
+      - name: Get modified files
+        id: modified_files
+        run: |
+          files=$(gh pr diff ${{ github.event.pull_request.number }} --name-only)
+          echo $files
+          echo "::set-output name=files::$files"
+      - name: Destination translation files are unmodified
+        run: |
+          exit_code=0
+          for file in ${{ steps.modified_files.outputs.files }}; do
+              if [[ $file == translation/dest/* ]]; then
+                  echo "Error: $file was modified"
+                  exit_code=1
+              fi
+          done
+          if [ $exit_code -ne 0 ]; then
+              echo "The files in translation/dest are automatically generated from Crowdin and should not be modified manually. Changes to these strings should be done at https://crowdin.com/project/lichess";
+          fi
+          exit $exit_code
